### ISSUE TITLE
Error: FileReader.readAsArrayBuffer is not implemented

### ISSUE THREAD

**Issue by JoonJoon123** [infinitered/nsfwjs-mobile#9]
Hi @GantMan @kevinvangelder ,

I tried this code in a new react native project but I was getting this error. 
I used react-native 0.61.5 and react 16.9.0 to produce this error.

[Unhandled promise rejection: Error: FileReader.readAsArrayBuffer is not implemented]
- node_modules/react-native/Libraries/Blob/FileReader.js:84:20 in readAsArrayBuffer
- node_modules/react-native/Libraries/vendor/core/whatwg-fetch.js:220:29 in readBlobAsArrayBuffer

**Comment by kevinvangelder** [comment]
I feel like I had to write a shim for this and maybe I didn't do an upstream PR. Unfortunately I won't have access to the computer I built this project on for the next week so I'm not currently able to check. Can you try with react 16.9.0 and react-native 0.60.5 and see if you get a different result?

**Comment by GantMan** [comment]
I'll keep watching this ticket.

**Comment by kevinvangelder** [comment]
@JoonJoon123 I had some spare time so I tried running this with the default package versions and everything appears to be running correctly.

**Comment by JoonJoon123** [comment]
Hey @kevinvangelder ,

I was able to successfully run the app on my iPhone. Thanks for the help.

I will close this issue.

**Comment by RobinBobin** [comment]
Hi!
I'm having the same issue under Android 9: `Error: FileReader.readAsArrayBuffer is not implemented`.
react: 16.13.1.
react-native: 0.63.3.
